### ISSUE TITLE
Convert Abstract Effect class into Interface

### ISSUE THREAD

**Issue by zibuk** [commonsguy/cwac-richedit#10]
I am implementing  a rich text editor and would like to use  richedit library as a foundation.
I have to implement several effects that are not supported by a library: bulleted list and a link.
I was planning to extend a base Effect class and implement missing effects but found that all methods in Effect class are package private that means I cannot extend Effect class. A simple change form Abstract class to interface would make it possible to create effects that are not implemented by richtext library.
  Also I found a very useful method applyToSpannable() on StyleEffect and SimpleBooleanEffect classes again it is a package private method. Changing scope of this method to protected will simplify subclass implementation

**Comment by commonsguy** [comment]
I am not ready to make `Effect` an interface, but I did make the methods on `Effect` `public` in v0.5.0. Similarly, I am not ready to `applyToSpannable()` part of the public API.
