### ISSUE TITLE
Bullet list spreads to text before it

### ISSUE THREAD

**Issue by pchupik** [commonsguy/cwac-richedit#23]
Steps:
1 Enter content with simple text and than bullet list e.g. form html `hello<br/><ul><li>list</li></ul>` like:
>hello
>* list

2 Put cursor in the end of the list 
3 Press Enter two times

Expected: 
>hello
>* list
>* 
>* 

Actual Result:
text before list is marked with bullet, as list 
>* hello
>* list
>* 
>*

**Comment by commonsguy** [comment]
Change integrated in v0.5.2. My apologies for the extensive delay.
