### ISSUE TITLE
<font color="..."> is deprecated internationally.

### ISSUE THREAD

**Issue by XinyueZ** [commonsguy/cwac-richedit#24]
I don't agree that the tag should be supported by the library. Instead it'd be better that <span> will be used to color elements.

**Comment by commonsguy** [comment]
I went with `<font color="...">` to match [what `Html.fromHtml()` and `Html.toHtml()` use](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/text/Html.java). You can also [replace that conversion with your own rule](https://github.com/commonsguy/cwac-richedit#customizing-the-conversion).

**Comment by XinyueZ** [comment]
thx
