### ISSUE TITLE
Bug: formatting options appear only after adding a link

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [commonsguy/cwac-richedit#34]
Steps:
1. Run the "demo" sample.
2. Write some text.
3. Mark it.
4. choose to format it.
5. Notice nothing happens.
6. Choose to add a link.
7. Notice that now the formatting options appear.

Attached video:
[device-2018-02-11-164310.zip](https://github.com/commonsguy/cwac-richedit/files/1714464/device-2018-02-11-164310.zip)

**Comment by commonsguy** [comment]
Thanks! But, this project is discontinued. I suggest that you use some other component.

**Comment by AndroidDeveloperLB** [comment]
Sadly each library out there has issues I've found, and even lacks basic options that I'm quite certain I will be required to have:
- https://github.com/mthli/Knife/issues/18 ,https://github.com/mthli/Knife/issues/19
- https://github.com/mr5/icarus-android/issues/37
- https://github.com/1gravity/Android-RTEditor/issues/126 , https://github.com/1gravity/Android-RTEditor/issues/127
- https://github.com/square1-io/rich-text-android/issues/3 - can't even import, but I'm sure I will find other issues
- https://github.com/daothanhduy305/KRichEditor/issues/4 , https://github.com/daothanhduy305/KRichEditor/issues/5 

Let alone issues other developers have found...

How hard is it to make one? Maybe I could do it from scratch...
Or maybe use a Web solution? Surely HTML5 is mature enough for this, no? I'm required to convert to/from HTML anyway, so could it be good enough?

I've looked at what Google did on Google Docs and it's really great. But I don't think it's open sourced :(

**Comment by commonsguy** [comment]
> How hard is it to make one?

Given manufacturer tweaks and the continuing evolution of `EditText`, it is difficult.

> Or maybe use a Web solution? 

Most of the ones that I have seen on the Android Arsenal use a `WebView`.

**Comment by AndroidDeveloperLB** [comment]
Are you familiar with a good one? What did you search on Android Arsenal? I actually didn't find many there...
Maybe I could use one that's intended for mobile, via a web browser, and somehow communicate with it via JavaScript.

I need one that offers:
1. Text style : bold, italic, underline
2. Link
3. Image
4. Alignment (right, left, center)
5. Lists (numbers&bullets)
6. Import&export from&to HTML.
7. Good RTL support.

Rest of the things you can think of are bonuses.

**Comment by commonsguy** [comment]
> What did you search on Android Arsenal?

A search on "rich" turns up:

- https://android-arsenal.com/details/1/2870
- https://android-arsenal.com/details/1/1696

plus KRichEditor and Knife that you linked to.

A search on "editor" turns up:

- https://android-arsenal.com/details/1/6207
- https://android-arsenal.com/details/1/3392

plus KRichEditor, Knife, and others that I linked to above.

**Comment by AndroidDeveloperLB** [comment]
Thank you. Will try them out. 
I hope one of them will work well.

**Comment by AndroidDeveloperLB** [comment]
Seems they also have issues:
- https://github.com/AvinashSKaranth/android-summernote/issues/10 - can't import
- https://github.com/jkennethcarino/RTextEditorView/issues/3  , https://github.com/jkennethcarino/RTextEditorView/issues/2
- https://github.com/wasabeef/richeditor-android/issues/157 - can't import
- https://github.com/SpongeBobSun/PoorEdit/issues/6 , and it lacks a lot of features.

I guess I will just have to choose the one with least issues.
