### ISSUE TITLE
Unnecessary underline

### ISSUE THREAD

**Issue by dovahkiin98** [commonsguy/cwac-richedit#35]
When I write a simple text line "note", the toXhtml() method always returns a text with <u></u> in it, even tho I've put no styling to the content.

example:
```
note
this
is
a
note
```
output:
```
<u><u><u><u>note<br/>this<br/>is<br/>a<br/></u></u></u></u><u>note</u>
```

**Comment by commonsguy** [comment]
As is noted on the project home page, this project is discontinued, pending some possible future from-scratch rewrite.
